language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - chmod +x install_pyqt.sh
  - ./install_pyqt.sh
  - cd ../D2ModdinPyClient

install:
  - pip install -r requirements.txt

script:
  - cd tests
  - python runner.py